services:
  lottery-codex:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: lottery-codex:latest
    container_name: lottery-codex
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${BACKEND_PATH}:/var/www/html/backend:rw
    environment:
      - TZ=${TZ}